export const AJAX_REQUEST = 'AJAX_REQUEST';
export const AJAX_RECEIVE = 'AJAX_RECEIVE';
export const AJAX_FAIL = 'AJAX_FAIL';

export const REQUEST_UPDATE_VALUE = 'REQUEST_UPDATE_VALUE';
export const REQUEST_MAKE_REQUEST = 'REQUEST_MAKE_REQUEST';